"""add absent_count to attendance_records

Revision ID: 099c9be931df
Revises: ffd22351ebfc
Create Date: 2026-06-30 21:45:36.482792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099c9be931df'
down_revision: Union[str, Sequence[str], None] = 'ffd22351ebfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('absent_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_records', 'absent_count')
    # ### end Alembic commands ###
