"""add year and semester to sections

Revision ID: ffd22351ebfc
Revises: 66c79db4f234
Create Date: 2026-06-30 21:30:37.690574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd22351ebfc'
down_revision: Union[str, Sequence[str], None] = '66c79db4f234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('year', sa.String(), nullable=False))
    op.add_column('sections', sa.Column('semester', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_dept_section'), 'sections', type_='unique')
    op.create_unique_constraint('uq_dept_section_year_sem', 'sections', ['department_id', 'name', 'year', 'semester'])
    op.drop_column('sections', 'advisor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('advisor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_dept_section_year_sem', 'sections', type_='unique')
    op.create_unique_constraint(op.f('uq_dept_section'), 'sections', ['department_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_column('sections', 'semester')
    op.drop_column('sections', 'year')
    # ### end Alembic commands ###
